services:
  product-service:
    build: .
    container_name: product-service
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product_db
      SPRING_DATASOURCE_USERNAME: productservice_user
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: postgres:18
    container_name: product-service-db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: productservice_user
      POSTGRES_PASSWORD: root
      TZ: Asia/Kolkata
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
